"""Generate docs/INDEX.md from evidence, so it cannot quietly go stale.

`docs/` holds 124 files. Eleven describe the current model; the rest are dated
records of how it got here. Nothing said which was which, and a reader had to
guess from filenames and dates - which is how the active forecast path came to
depend on an artifact in a directory named `..._rejected_...` without anyone
noticing.

The split is derived, never hand-maintained:

* **current state** - carries the ``<!-- active-model-version: -->`` marker that
  `audit_version_consistency.py` already pins to the pointer;
* **live reference** - no marker, but reachable from a current-state document or
  named by a script, config or workflow;
* **record** - everything else: dated experiments, diagnoses, superseded final
  models and frozen baselines.

A document that is neither marked nor referenced is a record by construction, so
the index cannot claim currency for something nothing points at.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "INDEX.md"
MARKER = re.compile(r"<!--\s*active-model-version:\s*(v\d+)\s*-->")
DATED = re.compile(r"_(20\d{6})\.(?:md|json)$")
#: Dated files group under these prefixes; the rest fall to "other records".
FAMILIES = (
    ("EXPERIMENT_", "Experiments"),
    ("DIAGNOSIS_", "Diagnoses"),
    ("FINAL_MODEL_", "Superseded final models"),
    ("GITHUB_BASELINE_", "Frozen repository baselines"),
    ("ACTIVE_", "Superseded promotions"),
    ("AUTOMATIC_", "Automatic-control development"),
    ("STANCE_", "Stance-model audits"),
    ("CURRENT_MODEL_PERFORMANCE_", "Dated performance snapshots"),
)


def _tracked() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], cwd=ROOT, check=True, capture_output=True
    ).stdout
    return [i.decode("utf-8").replace("\\", "/") for i in out.split(b"\0") if i]


def _referenced_paths(sources: list[str]) -> set[str]:
    """Every docs/ path named by code, config, workflows or a current document."""

    referenced: set[str] = set()
    for relative in sources:
        try:
            text = (ROOT / relative).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for hit in re.findall(r"[\w./-]*docs/[\w.-]+\.(?:md|json)", text):
            referenced.add("docs/" + hit.split("docs/")[-1])
        if relative.startswith("docs/"):
            # sibling links inside docs/ are written without the prefix
            for hit in re.findall(r"\(([\w.-]+\.(?:md|json))\)", text):
                referenced.add(f"docs/{hit}")
    return referenced


def classify() -> tuple[list[str], list[str], list[str]]:
    tracked = _tracked()
    docs = sorted(p for p in tracked if p.startswith("docs/") and "/" not in p[5:])
    scanned = [
        p
        for p in tracked
        if p.endswith((".py", ".yml", ".yaml", ".json", ".toml", ".in"))
        or p in {"README.md", "CONTRIBUTING.md", "SECURITY.md", "STRUCTURE.md"}
    ]
    current = [
        p
        for p in docs
        if p.endswith(".md") and MARKER.search((ROOT / p).read_text(encoding="utf-8", errors="replace"))
    ]
    referenced = _referenced_paths(scanned + current)
    reference, record = [], []
    for p in docs:
        if p in current:
            continue
        (reference if p in referenced and not DATED.search(p) else record).append(p)
    return current, reference, record


def render(current: list[str], reference: list[str], record: list[str]) -> str:
    version = MARKER.search(
        (ROOT / "docs/ARCHITECTURE.md").read_text(encoding="utf-8")
    ).group(1)
    lines = [
        f"<!-- active-model-version: {version} -->",
        "# Document index",
        "",
        "Generated by `scripts/build_docs_index.py`; do not edit by hand.",
        "",
        "`docs/` keeps the record of how the model got here alongside the",
        "documents describing what it is now. This index separates them by",
        "evidence rather than by filename: a document is **current** when it",
        "carries the active-version marker the version audit pins, **reference**",
        "when something current or executable points at it, and a **record**",
        "otherwise.",
        "",
        f"## Current state ({len(current)})",
        "",
        "These describe the active model. `scripts/audit_version_consistency.py`",
        "fails if any of them stops declaring the pointer's version.",
        "",
    ]
    lines += [f"- [{Path(p).name}]({Path(p).name})" for p in current]
    lines += [
        "",
        f"## Live reference ({len(reference)})",
        "",
        "No active-version marker, but reachable from a current document or named",
        "by code, configuration or a workflow.",
        "",
    ]
    lines += [f"- [{Path(p).name}]({Path(p).name})" for p in reference]
    lines += [
        "",
        f"## Records ({len(record)})",
        "",
        "Dated evidence of past work. Accurate for the state they describe and",
        "**not** to be read as current. Where a record was later overturned, the",
        "document itself says so rather than being deleted.",
        "",
    ]
    remaining = list(record)
    for prefix, title in FAMILIES:
        group = [p for p in remaining if Path(p).name.startswith(prefix)]
        if not group:
            continue
        remaining = [p for p in remaining if p not in group]
        lines += [f"### {title} ({len(group)})", ""]
        lines += [f"- [{Path(p).name}]({Path(p).name})" for p in group]
        lines.append("")
    if remaining:
        lines += [f"### Other records ({len(remaining)})", ""]
        lines += [f"- [{Path(p).name}]({Path(p).name})" for p in remaining]
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def build(output: Path = OUTPUT) -> str:
    payload = render(*classify())
    output.write_bytes(payload.encode("utf-8"))
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed index differs from a fresh generation",
    )
    args = parser.parse_args()
    if args.check:
        fresh = render(*classify())
        current = args.output.read_bytes().decode("utf-8") if args.output.is_file() else ""
        if fresh != current:
            raise SystemExit(
                f"{args.output.relative_to(ROOT).as_posix()} is stale; "
                "regenerate with python scripts/build_docs_index.py"
            )
        print("[docs index: current]")
        return
    build(args.output)
    print(args.output.relative_to(ROOT).as_posix())


if __name__ == "__main__":
    main()
