"""Freeze the V25 pipeline as it runs inside the external-model boundary.

The prospective harness proves it does not alter history by reproducing a
frozen artifact byte for byte. From V28 onward it runs inside
``external_model_free_runtime()``, which blocks the automatic issue seeds, so
its history legitimately differs from the V25 artifact frozen before that
boundary existed - and the check has been failing on every run since.

The repair is to compare against history built under the same runtime. This
script produces that baseline by running the **V25 model runner** inside the
boundary, not the prospective harness. That distinction is the whole point: the
guard then still checks the harness against the model, exactly as before, with
only the runtime aligned. A baseline generated by the harness itself would
reduce the check to the harness reproducing itself.

The baseline is a verification reference, not a promoted model. It is never
pointed at by the active-model pointer and never scored.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from presidential_issue_engine.external_model_free_runtime import (  # noqa: E402
    external_model_free_runtime,
)
from scripts import run_active_presidential_model_v25 as v25  # noqa: E402

OUTPUT_DIR = ROOT / "outputs" / "external_model_free_v25_baseline"
PREDICTIONS = "nested_predictions.csv"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build(output_dir: Path = OUTPUT_DIR) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    with external_model_free_runtime():
        v25.run(output_dir=output_dir)
    manifest = {
        "schema": "external_model_free_baseline_v1",
        "role": "prospective_harness_history_reference",
        "pipeline": "v25",
        "runtime": "external_model_free",
        "promoted": False,
        "scored": False,
        "post_2022_outcomes_used": False,
        "prediction_sha256": _sha256(output_dir / PREDICTIONS),
        "why": (
            "The V25 artifact was frozen before the external-model boundary "
            "existed, so a run inside the boundary cannot reproduce it. This is "
            "the same pipeline under the runtime the prospective harness "
            "actually uses."
        ),
    }
    (output_dir / "baseline_manifest.json").write_bytes(
        (json.dumps(manifest, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    )
    return output_dir


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    args = parser.parse_args()
    destination = build(args.output_dir)
    print(destination.relative_to(ROOT).as_posix())
    print(f"prediction_sha256={_sha256(destination / PREDICTIONS)}")


if __name__ == "__main__":
    main()
